product-name: cf
network-properties:
  singleton_availability_zone:
    name: ((az1))
  other_availability_zones:
  - name: ((az1))
  - name: ((az2))
  - name: ((az3))
  network:
    name: pas
product-properties:
  .cloud_controller.system_domain:
    value: sys.((subdomain-name)).((domain-name))
  .cloud_controller.apps_domain:
    value: apps.((subdomain-name)).((domain-name))
  .properties.stack_migration_acknowledgement  :
    value: X
  .properties.networking_poe_ssl_certs:
    value:
    - name: certificate
      certificate:
        cert_pem: ((domain-crt))
        private_key_pem: ((domain-key))
  .properties.metric_registrar_enabled:
    value: true
  .properties.metric_registrar_scrape_interval_in_seconds:
    value: 15
   
  .properties.haproxy_forward_tls:
    value: disable
  .ha_proxy.skip_cert_verify:
    value: true
  .properties.security_acknowledgement:
    value: X
  .uaa.service_provider_key_credentials:
    value:
      cert_pem: ((domain-crt))
      private_key_pem: ((domain-key))
  .properties.credhub_key_encryption_passwords:
    value:
    - name: default
      key:
        secret: ((om-password))
      primary: true
  .mysql_monitor.recipient_email:
    value: anyone@someone.com
errand-config:
  deploy-autoscaler:
    post-deploy-state: true
  deploy-notifications:
    post-deploy-state: true
  deploy-notifications-ui:
    post-deploy-state: true
  nfsbrokerpush:
    post-deploy-state: false
  test-autoscaling:
    post-deploy-state: true
  smoke_tests:
    post-deploy-state: true
  push-apps-manager:
    post-deploy-state: true
  push-usage-service:
    post-deploy-state: true
  metric_registrar_smoke_test:
    post-deploy-state: true

resource-config:
  compute:
    instances: 3
    instance_type:
      id: 2xlarge.disk
  control:
    instances: 2
    elb_names:
    - tcp:((subdomain-name))-cf-ssh
  router:
    instances: 2
    elb_names:
    - tcp:((subdomain-name))-cf-ws
    - http:((subdomain-name))-httpslb
